spring.application.name=cineVaultApp

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# Connection Pooling (Hikari)
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# TMDB API
tmdb.base-url=${TMDB_URL}
# Fallback TMDB API URL
fallback.tmdb.base-url=${FALLBACK_TMDB_URL}
tmdb.api-key=${TMDB_API_KEY}

# JIKAN Anime API
jikan.base-url=${JIKAN_BASE_URL}

# Google oAuth2 Client id
google.client-id=${GOOGLE_CLIENT_ID}
